package org.searlelab.msrawjava.io;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.sql.SQLException;
import java.util.ArrayList;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import org.searlelab.msrawjava.model.FragmentScan;

class MGFOutputFileTest {

	@TempDir
	Path tmp;

	private static FragmentScan ms2(String name, int index, float rtSeconds, double isoLo, double isoHi, double[] mz, float[] inten, float[] ims, byte charge) {
		// spectrumName, precursorName, spectrumIndex, scanStartTime, fraction, ionInjectionTime,
		// isoLow, isoHigh, mz[], intensity[], ims[], charge, scanWindowLower, scanWindowUpper
		return new FragmentScan(name, "prec", index, rtSeconds, 0, null, isoLo, isoHi, mz, inten, ims, charge, 0.0, 3000.0);
	}

	@Test
	void writesSingleMs2Block_withMetadataAndFormatting() throws IOException, SQLException, Exception {
		MGFOutputFile writer=new MGFOutputFile();
		assertEquals(".mgf", writer.getFileExtension());

		writer.openFile();
		writer.setFileName("tiny_run.mzML", "/data/tiny_run.mzML");

		// One MS2 with a mix of intensities (<=0 filtered), IMS present (median used), and positive charge
		double[] mz=new double[] {100.0, 200.1234567, 300.0};
		float[] in=new float[] {0.0f, 10.49f, -1.0f};
		float[] im=new float[] {1.0f, 2.0f, 3.0f}; // median = 2.0
		FragmentScan fs=ms2("scan-42", 42, 12.345f, 499.95, 500.05, mz, in, im, (byte)+2);

		ArrayList<FragmentScan> stripes=new ArrayList<>();
		stripes.add(fs);

		writer.addSpectra(new ArrayList<>(), stripes);

		Path out=tmp.resolve("out.mgf");
		writer.saveAsFile(out.toFile());

		// Read and assert content
		String mgf=Files.readString(out, StandardCharsets.UTF_8);

		// Header comments
		assertTrue(mgf.contains("# MGF generated by org.searlelab.msrawjava.io.MGFOutputFile"));
		assertTrue(mgf.contains("# FILE_NAME=tiny_run.mzML"));
		assertTrue(mgf.contains("# SOURCE_PATH=/data/tiny_run.mzML"));

		// Block structure and required fields
		assertTrue(mgf.contains("BEGIN IONS"));
		assertTrue(mgf.contains("END IONS"));
		assertTrue(mgf.contains("TITLE=scan-42"));
		assertTrue(mgf.contains("SCANS=42"));
		assertTrue(mgf.contains("MSLEVEL=2"));

		// RT formatting
		assertTrue(mgf.contains("RTINSECONDS=12.345"), "RT should be printed with 3 decimals");

		// Precursor m/z is center of isolation window
		double pepmass=(499.95+500.05)/2.0;
		assertTrue(mgf.contains(String.format("PEPMASS=%.6f", pepmass)), "PEPMASS should be center m/z with 6 decimals");

		// Ion mobility median included
		assertTrue(mgf.contains("ION_MOBILITY=2.0"));

		// Charge formatting: absolute value with + sign
		assertTrue(mgf.contains("CHARGE=2+"));

		// Peaks: only intensities > 0 are printed; formatting m/z(6dp) and intensity(1dp)
		// Second entry is the only positive one
		String expectedPeak=String.format("%.6f	%.1f", 200.1234567, 10.49f);
		assertTrue(mgf.contains(expectedPeak), "Expected formatted peak line should be present");
		// Ensure zero/negative intensities are not printed
		assertFalse(mgf.contains(String.format("%.6f", 100.0)+"\t0.0"));
		assertFalse(mgf.contains(String.format("%.6f", 300.0)+"\t-1.0"));
	}

	@Test
	void writesMultipleBlocks_andHandlesNegativeCharge_andNoIMS() throws Exception {
		MGFOutputFile writer=new MGFOutputFile();
		writer.openFile();
		writer.setFileName("foo", "bar");

		// First MS2: no IMS array, negative charge
		FragmentScan a=ms2("A", 7, 1.0f, 399.0, 401.0, new double[] {150.0, 151.0}, new float[] {5.0f, 0.0f}, null, (byte)-3);

		// Second MS2: empty peaks, zero charge
		FragmentScan b=ms2("B", 8, 2.0f, 499.0, 501.0, new double[] {}, new float[] {}, null, (byte)0);

		ArrayList<FragmentScan> stripes=new ArrayList<>();
		stripes.add(a);
		stripes.add(b);
		writer.addSpectra(new ArrayList<>(), stripes);

		Path out=tmp.resolve("two.mgf");
		writer.saveAsFile(out.toFile());
		String mgf=Files.readString(out, StandardCharsets.UTF_8);

		// Two blocks present
		assertTrue(mgf.contains("TITLE=A"));
		assertTrue(mgf.contains("TITLE=B"));

		// CHARGE formatting for negative value
		assertTrue(mgf.contains("CHARGE=3-"));

		// Peaks for A: only first peak printed (second intensity is zero)
		assertTrue(mgf.contains(String.format("%.6f	%.1f", 150.0, 5.0f)));
		assertFalse(mgf.contains(String.format("%.6f	%.1f", 151.0, 0.0f)));
	}
}
