package org.searlelab.msrawjava.io;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Map;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.Assumptions;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import org.searlelab.msrawjava.io.tims.BrukerTIMSFile;
import org.searlelab.msrawjava.model.FragmentScan;
import org.searlelab.msrawjava.model.PrecursorScan;
import org.searlelab.msrawjava.model.Range;
import org.searlelab.msrawjava.model.WindowData;

class MGFOutputFileIT {

	private static final Path D_PATH=Path.of("src", "test", "resources", "rawdata", "230711_idleflow_400-1000mz_25mz_diaPasef_10sec.d");

	@TempDir
	Path tmp;

	private BrukerTIMSFile openFileOrSkip() throws Exception {
		Assumptions.assumeTrue(Files.exists(D_PATH), "Fixture .d not present: "+D_PATH);
		BrukerTIMSFile file=new BrukerTIMSFile();
		file.openFile(D_PATH);
		return file;
	}

	@AfterEach
	void cleanup() {
		// nothing to clean here; @TempDir handles files
	}

	@Test
	void writesMGF_forSubsetOfMS2Blocks_withExpectedHeadersAndCounts() throws Exception {
		BrukerTIMSFile file=openFileOrSkip();

		// Enumerate ranges (DIA stripes) or fallback to a single wide window
		Map<Range, WindowData> rangeMap=file.getRanges();
		ArrayList<Range> ranges=new ArrayList<>(rangeMap.keySet());
		if (ranges.isEmpty()) {
			ranges.add(new Range(0f, Float.MAX_VALUE));
		}
		Collections.sort(ranges);

		// Collect a small subset of MS2 stripes (keep runtime small)
		ArrayList<FragmentScan> ms2=new ArrayList<>();
		final int MAX_SCANS=10;
		for (Range r : ranges) {
			ArrayList<FragmentScan> chunk=file.getStripes(r, 0.0f, Float.MAX_VALUE, false);
			for (FragmentScan s : chunk) {
				ms2.add(s);
				if (ms2.size()>=MAX_SCANS) break;
			}
			if (ms2.size()>=MAX_SCANS) break;
		}

		// Sanity: we must have at least one MS2 to proceed
		Assumptions.assumeTrue(!ms2.isEmpty(), "No MS2 found in fixture; cannot run IT");

		// Write MGF
		MGFOutputFile writer=new MGFOutputFile();
		writer.openFile();
		writer.setFileName(D_PATH.getFileName().toString(), D_PATH.toString());
		writer.addSpectra(new ArrayList<PrecursorScan>(), ms2);

		Path out=tmp.resolve("subset.mgf");
		writer.saveAsFile(out.toFile());
		writer.close();

		// Read produced file
		String mgf=Files.readString(out, StandardCharsets.UTF_8);

		// Global headers present
		assertTrue(mgf.contains("# MGF generated by org.searlelab.msrawjava.io.MGFOutputFile"));
		assertTrue(mgf.contains("# FILE_NAME="+D_PATH.getFileName()));
		assertTrue(mgf.contains("# SOURCE_PATH="+D_PATH));

		// Per-block invariants
		long beginBlocks=mgf.lines().filter(l -> l.equals("BEGIN IONS")).count();
		long endBlocks=mgf.lines().filter(l -> l.equals("END IONS")).count();
		long mslevels=mgf.lines().filter(l -> l.equals("MSLEVEL=2")).count();
		assertEquals(ms2.size(), beginBlocks, "BEGIN IONS blocks should equal number of MS2 written");
		assertEquals(ms2.size(), endBlocks, "END IONS blocks should equal number of MS2 written");
		assertEquals(ms2.size(), mslevels, "MSLEVEL=2 lines should equal number of MS2 written");

		// Check first scan's specific fields (TITLE/SCANS/PEPMASS/RT)
		FragmentScan first=ms2.get(0);
		String expectedTitle=(first.getSpectrumName()==null||first.getSpectrumName().isEmpty())?"scan="+first.getSpectrumIndex():first.getSpectrumName();
		assertTrue(mgf.contains("TITLE="+expectedTitle));
		assertTrue(mgf.contains("SCANS="+first.getSpectrumIndex()));
		assertTrue(mgf.contains(String.format("RTINSECONDS=%.3f", first.getScanStartTime())));
		assertTrue(mgf.contains(String.format("PEPMASS=%.6f", first.getPrecursorMZ())));

		// Expect at least one peak line (m/z TAB intensity) somewhere in the file
		assertTrue(mgf.contains("\t")||mgf.contains("	"), "At least one peak line should be present");

		// Close vendor file
		file.close();
	}
}
