package org.searlelab.msrawjava.io;

import java.io.File;
import java.io.IOException;
import java.io.PrintWriter;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.Optional;

import org.searlelab.msrawjava.model.FragmentScan;
import org.searlelab.msrawjava.model.PrecursorScan;
import org.searlelab.msrawjava.model.Range;
import org.searlelab.msrawjava.model.WindowData;

public class MGFOutputFile implements OutputSpectrumFile {

	public static final String MGF_EXTENSION=".mgf";
	private Path tempPath=null;
	private PrintWriter writer=null;

	@Override
	public String getFileExtension() {
		return MGF_EXTENSION;
	}

	@Override
	public void setRanges(HashMap<Range, WindowData> ranges) {
		// ignore
	}

	@Override
	public void addMetadata(Map<String, String> data) throws IOException, SQLException {
		// ignore
	}

	@Override
	public void saveAsFile(File userFile) throws IOException, SQLException {
		if (writer!=null) {
			writer.flush();
			writer.close();
		}

		File parent=userFile.getParentFile();
		if (parent!=null) {
			Files.createDirectories(parent.toPath());
		}

		Files.move(tempPath, userFile.toPath(), StandardCopyOption.REPLACE_EXISTING);
	}

	@Override
	public void setFileName(String fileName, String fileLocation) throws IOException, SQLException {
		writer.println("# MGF generated by org.searlelab.msrawjava.io.MGFOutputFile");
		if (fileName!=null) {
			writer.println("# FILE_NAME="+fileName);
		}
		if (fileLocation!=null) {
			writer.println("# SOURCE_PATH="+fileLocation);
		}
		writer.println();
	}

	/**
	 * Stream spectra to the open temp file. Only MS2 are written (precursors ignored).
	 */
	@Override
	public void addSpectra(ArrayList<PrecursorScan> precursors, ArrayList<FragmentScan> stripes) throws Exception {
		for (FragmentScan msms : stripes) {
			writer.println("BEGIN IONS");

			String title=msms.getSpectrumName();
			if (title==null||title.isEmpty()) {
				title="scan="+msms.getSpectrumIndex();
			}
			writer.println("TITLE="+escapeTitle(title));
			writer.println("SCANS="+Integer.toString(msms.getSpectrumIndex()));
			writer.println(String.format("RTINSECONDS=%.3f", msms.getScanStartTime()));
			writer.println("MSLEVEL=2");
			writer.println(String.format("PEPMASS=%.6f", msms.getPrecursorMZ()));

			Optional<Float> ims=msms.getMedianIonMobility();
			if (ims.isPresent()) {
				writer.println("ION_MOBILITY="+ims.get());
			}

			int z=msms.getCharge();
			if (z!=0) {
				int abs=Math.abs(z);
				writer.println("CHARGE="+Integer.toString(abs)+(z>0?"+":"-"));
			}

			double[] mz=msms.getMassArray();
			float[] intensity=msms.getIntensityArray();
			for (int i=0; i<Math.min(mz.length, intensity.length); i++) {
				if (intensity[i]>0f) {
					writer.println(String.format("%.6f", mz[i])+"\t"+String.format("%.1f", intensity[i]));
				}
			}

			writer.println("END IONS");
			writer.println();
		}

		writer.flush();
	}

	@Override
	public void close() {
		try {
			if (writer!=null) {
				writer.flush();
				writer.close();
			}
		} finally {
			writer=null;
		}
	}

	public void openFile() throws IOException {
		tempPath=Files.createTempFile("mgf_stream_", getFileExtension());
		writer=new PrintWriter(tempPath.toFile());
	}

	private static String escapeTitle(String s) {
		return s.replace('\n', ' ').replace('\r', ' ').replace('\t', ' ');
	}
}